### ISSUE TITLE
LLM Pre-Training Details

### ISSUE THREAD

**Issue by rabiakonuk** [vateseif/l2o#4]
Thank you for sharing this great work. To further understand and potentially apply your methodologies, I have a few general questions regarding the LLM pre-training aspect:

1. **Data Sources**: What datasets were utilized for LLM pre-training?
2. **Pre-training Goals**: Could you outline the primary goals set for the LLM during pre-training?
3. **Overcoming Challenges**: Were there any notable challenges in the pre-training process, and how were they tackled?

Insights on these points would be greatly appreciated. Thanks for taking the time to address this inquiry.

Cheers!

**Comment by vateseif** [comment]
we use GPT4 via API without any additional fine-tuning. i believe any large model accessible via API has seen enough code (in particular `casadi` code) that it works well without the need of more tuning.
